jobe:
  restart: always
  build: .
  #volumes:
  #map container port 80 to host port 8000
  ports:
    - 3332:80
    - 3333:443
  #Command to put Apache in the foreground
  command:  /usr/sbin/apache2ctl -D FOREGROUND
